# Generated by Django 5.0.7 on 2024-07-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids')], max_length=10),
        ),
    ]
