# Generated by Django 5.0.7 on 2024-07-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids'), ('accessory', 'accessory')], max_length=10),
        ),
    ]
