# Generated by Django 5.0.7 on 2024-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids'), ('accessory', 'accessory'), ('phones', 'phones'), ('home-office', 'home-office'), ('supermarket', 'supermarket'), ('appliances', 'appliances'), ('games', 'games'), ('computer', 'computer'), ('health', 'health')], max_length=20),
        ),
    ]
